//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj1_MvcProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUSTERILER
    {
        public int MUSTERIID { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
