//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj1_MvcProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSEPETT
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> KullanıcıID { get; set; }
    
        public virtual TBLKULLANICI TBLKULLANICI { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
